services:
  app:
    container_name: copo-do-mundo-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    environment:
      - DEBUG=True
      - PORT=8501
      - HOST=0.0.0.0
    command: streamlit run main.py --server.port=8501 --server.address=0.0.0.0